version: '4.11.1'
services:
  web1:
    build: ./web1
    ports:
      - "8079:80"
  web2:
    build: ./web2
    ports:
      - "8080:80"
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: web1 web2 PipelineWebservice1
    command: --interval 1
